name: CI-Push-Master
on:
  push:
    tags:
      - 'v*'
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build Project
      run: mvn clean install

    - name: Upload Security Framework API Jar File
      uses: actions/upload-artifact@v1
      with:
        name: Semantic Version
        path: ./target/SemanticRelease-1.0-SNAPSHOT.jar

    - name: Release
      uses: docker://antonyurchenko/git-release:v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "false"
        ALLOW_TAG_PREFIX: "false"
      with:
        args: |
          build/*-amd64.zip