name: CI-Push-Master
on:
  push:

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-SemanticRelease-1.0-SNAPSHOT-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-SemanticRelease-1.0-SNAPSHOT-

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build Project
      run: mvn clean install

    - name: Upload Security Framework API Jar File
      uses: actions/upload-artifact@v1
      with:
        name: Semantic Version
        path: ./target/SemanticRelease-1.0-SNAPSHOT.jar

    - uses: BobAnkh/auto-generate-changelog@master
      with:
        REPO_NAME: 'BobAnkh/auto-generate-changelog'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: '/CHANGELOG.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'

    - name: Check CHANGELOG
      run: |
        cat .github/workflows