name: CI-Push-Master
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Release
      uses: docker://antonyurchenko/git-release@3.4.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "false"
        ALLOW_TAG_PREFIX: "false"
      with:
        args: |
            target/SemanticRelease-1.0-SNAPSHOT.jar
    