name: CI-Push-Master
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Run Unit Tests
      run: mvn clean install