name: CI-Push-Master
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Run Unit Tests
      run: mvn clean install

  - name: Upload Security Framework API Jar File
      uses: actions/upload-artifact@v1
      with:
        name: Semantic Version
        path: ./nova-auth-identity-provider-server/target/nova-auth-identity-provider-server-0.0.1.jar

    - name: Release
      uses: docker://antonyurchenko/git-release:3.4.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "false"
        ALLOW_TAG_PREFIX: "false"
      with:
        args: |
            target/SemanticRelease-1.0-SNAPSHOT.jar
    