on:
  push:
    branches:
      - main

      
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: mvn clean install

      - name: Copy jar file
        run: |
          cd ${GITHUB_WORKSPACE}/target
          cp SemanticRelease-1.0.0.jar ${GITHUB_WORKSPACE}

      - name: Create a Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          pwd
          ls
          npx semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}

      - name: Check Tag
        run: echo ${{ github.event.release.tag_name }}