on:
  push:
    branches:
      - beta
      - main
name: release-please
jobs:
  semantic-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
      - uses: beemojs/conventional-pr-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List Content
        run: ls -la

      - name: Run Unit Tests
        run: mvn clean install

      - name: Copy jar file
        run: |
          cd ${GITHUB_WORKSPACE}/target
          cp SemanticRelease-*.jar ${GITHUB_WORKSPACE}

      - name: Install npm
        run: npm install @semantic-release/exec

      - name: Create a Release
        if: github.event_name == 'push' #&& github.ref == 'refs/heads/beta'
        run: npx semantic-release --dry-run --no-ci
        env: 
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}

      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: Echo Alexandre
        run: echo ${{ steps.tag.outputs.result }}

      - name: Update Pom File
        if: github.event_name == 'push' #&& github.ref == 'refs/heads/beta'
        run: |
          echo ${{ github.event.release.tag_name }}
          echo ${{ steps.tagName.outputs.version }}
          mvn -B versions:set -DnewVersion=17.4.2 -DgenerateBackupPoms=false

      - name: List files stage
        run: |
          ls -la

      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          author_name: Alexandre
          author_email: marodrigues20@gmail.com
          branch: beta
          cwd: '.'
          message: 'New Version Pom file'
          add: 'pom.xml'