on:
  push:
    branches:
      - beta
      - master
name: release-please
jobs:
  semantic-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
      - uses: beemojs/conventional-pr-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List Content
        run: ls -la

      - name: Run Unit Tests
        run: mvn clean install

      - name: Copy jar file
        run: |
          cd ${GITHUB_WORKSPACE}/target
          cp SemanticRelease-*.jar ${GITHUB_WORKSPACE}

      - name: Install npm
        run: npm install @semantic-release/exec

      - name: Create a Release
        #if: github.event_name == 'push' && github.ref == 'refs/heads/beta'
        run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}