on:
  push:
    branches:
      - beta
      - main
name: release-please
jobs:
  semantic-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: mvn clean install

      - name: Copy jar file
        run: |
          cd ${GITHUB_WORKSPACE}/target
          cp SemanticRelease-*.jar ${GITHUB_WORKSPACE}

      - name: Install npm
        run: npm install @semantic-release/exec

      - name: Create a Release
        if: github.event_name == 'push' #&& github.ref == 'refs/heads/beta'
        run: npx semantic-release --dry-run --no-ci
        env: 
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}

      - name: Update Pom File
        if: github.event_name == 'push' #&& github.ref == 'refs/heads/beta'
        run: |
          echo ${{ github.event.release.tag_name }}
          mvn -B versions:set -DnewVersion=17.4.2 -DgenerateBackupPoms=false