on:
  push:
    branches:
      - main

      
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Create a Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}