on:
  release:
    branches:
      - main
name: update-mvn
jobs:
  semantic-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Check release tag_name
        run: echo ${{ github.event.release.tag_name }}

      - name: Update Maven Version
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false